//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Moma.IwtForumConverter.WsIwt {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CollaborativeSessionDescriptor", Namespace="http://schemas.datacontract.org/2004/07/VCS", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class CollaborativeSessionDescriptor : Moma.IwtForumConverter.WsIwt.CS2Object {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Moma.IwtForumConverter.WsIwt.Site SiteField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Moma.IwtForumConverter.WsIwt.Site Site {
            get {
                return this.SiteField;
            }
            set {
                if ((object.ReferenceEquals(this.SiteField, value) != true)) {
                    this.SiteField = value;
                    this.RaisePropertyChanged("Site");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CS2Object", Namespace="http://schemas.datacontract.org/2004/07/VCS", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Moma.IwtForumConverter.WsIwt.Site))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Moma.IwtForumConverter.WsIwt.CollaborativeSession))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Moma.IwtForumConverter.WsIwt.Post))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Moma.IwtForumConverter.WsIwt.Category))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Moma.IwtForumConverter.WsIwt.UserAccount))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Moma.IwtForumConverter.WsIwt.Message))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Moma.IwtForumConverter.WsIwt.CollaborativeSessionDescriptor))]
    public partial class CS2Object : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Site", Namespace="http://schemas.datacontract.org/2004/07/VCS", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Site : Moma.IwtForumConverter.WsIwt.CS2Object {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url {
            get {
                return this.UrlField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlField, value) != true)) {
                    this.UrlField = value;
                    this.RaisePropertyChanged("Url");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CollaborativeSession", Namespace="http://schemas.datacontract.org/2004/07/VCS", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class CollaborativeSession : Moma.IwtForumConverter.WsIwt.CS2Object {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Moma.IwtForumConverter.WsIwt.Post> PostsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Moma.IwtForumConverter.WsIwt.Site SiteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Moma.IwtForumConverter.WsIwt.UserAccount> UserAccountsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Moma.IwtForumConverter.WsIwt.Post> Posts {
            get {
                return this.PostsField;
            }
            set {
                if ((object.ReferenceEquals(this.PostsField, value) != true)) {
                    this.PostsField = value;
                    this.RaisePropertyChanged("Posts");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Moma.IwtForumConverter.WsIwt.Site Site {
            get {
                return this.SiteField;
            }
            set {
                if ((object.ReferenceEquals(this.SiteField, value) != true)) {
                    this.SiteField = value;
                    this.RaisePropertyChanged("Site");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url {
            get {
                return this.UrlField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlField, value) != true)) {
                    this.UrlField = value;
                    this.RaisePropertyChanged("Url");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Moma.IwtForumConverter.WsIwt.UserAccount> UserAccounts {
            get {
                return this.UserAccountsField;
            }
            set {
                if ((object.ReferenceEquals(this.UserAccountsField, value) != true)) {
                    this.UserAccountsField = value;
                    this.RaisePropertyChanged("UserAccounts");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Post", Namespace="http://schemas.datacontract.org/2004/07/VCS", IsReference=true)]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Moma.IwtForumConverter.WsIwt.Message))]
    public partial class Post : Moma.IwtForumConverter.WsIwt.CS2Object {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Moma.IwtForumConverter.WsIwt.Category> CategoriesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreationDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Moma.IwtForumConverter.WsIwt.UserAccount CreatorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Moma.IwtForumConverter.WsIwt.Post ReplyOfField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Moma.IwtForumConverter.WsIwt.Category> Categories {
            get {
                return this.CategoriesField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoriesField, value) != true)) {
                    this.CategoriesField = value;
                    this.RaisePropertyChanged("Categories");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreationDate {
            get {
                return this.CreationDateField;
            }
            set {
                if ((this.CreationDateField.Equals(value) != true)) {
                    this.CreationDateField = value;
                    this.RaisePropertyChanged("CreationDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Moma.IwtForumConverter.WsIwt.UserAccount Creator {
            get {
                return this.CreatorField;
            }
            set {
                if ((object.ReferenceEquals(this.CreatorField, value) != true)) {
                    this.CreatorField = value;
                    this.RaisePropertyChanged("Creator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Moma.IwtForumConverter.WsIwt.Post ReplyOf {
            get {
                return this.ReplyOfField;
            }
            set {
                if ((object.ReferenceEquals(this.ReplyOfField, value) != true)) {
                    this.ReplyOfField = value;
                    this.RaisePropertyChanged("ReplyOf");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Category", Namespace="http://schemas.datacontract.org/2004/07/VCS", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Category : Moma.IwtForumConverter.WsIwt.CS2Object {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserAccount", Namespace="http://schemas.datacontract.org/2004/07/VCS", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class UserAccount : Moma.IwtForumConverter.WsIwt.CS2Object {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] AvatarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Moma.IwtForumConverter.WsIwt.Gender GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Moma.IwtForumConverter.WsIwt.Role RoleField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Age {
            get {
                return this.AgeField;
            }
            set {
                if ((this.AgeField.Equals(value) != true)) {
                    this.AgeField = value;
                    this.RaisePropertyChanged("Age");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Avatar {
            get {
                return this.AvatarField;
            }
            set {
                if ((object.ReferenceEquals(this.AvatarField, value) != true)) {
                    this.AvatarField = value;
                    this.RaisePropertyChanged("Avatar");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Moma.IwtForumConverter.WsIwt.Gender Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((this.GenderField.Equals(value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Moma.IwtForumConverter.WsIwt.Role Role {
            get {
                return this.RoleField;
            }
            set {
                if ((this.RoleField.Equals(value) != true)) {
                    this.RoleField = value;
                    this.RaisePropertyChanged("Role");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Message", Namespace="http://schemas.datacontract.org/2004/07/ForumSessionExport", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Message : Moma.IwtForumConverter.WsIwt.Post {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<int> RepliesIdsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ReplyOfIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<int> RepliesIds {
            get {
                return this.RepliesIdsField;
            }
            set {
                if ((object.ReferenceEquals(this.RepliesIdsField, value) != true)) {
                    this.RepliesIdsField = value;
                    this.RaisePropertyChanged("RepliesIds");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ReplyOfId {
            get {
                return this.ReplyOfIdField;
            }
            set {
                if ((this.ReplyOfIdField.Equals(value) != true)) {
                    this.ReplyOfIdField = value;
                    this.RaisePropertyChanged("ReplyOfId");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Gender", Namespace="http://schemas.datacontract.org/2004/07/VCS")]
    public enum Gender : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Neutral = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Female = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Male = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Role", Namespace="http://schemas.datacontract.org/2004/07/VCS")]
    public enum Role : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Teacher = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Student = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://momanet.it/iwt/Forum/", ConfigurationName="WsIwt.CollaborativeSessionExportService")]
    public interface CollaborativeSessionExportService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://momanet.it/iwt/Forum/CollaborativeSessionExportService/AvailableCollaborat" +
            "iveSessions", ReplyAction="http://momanet.it/iwt/Forum/CollaborativeSessionExportService/AvailableCollaborat" +
            "iveSessionsResponse")]
        System.Collections.Generic.List<Moma.IwtForumConverter.WsIwt.CollaborativeSessionDescriptor> AvailableCollaborativeSessions();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://momanet.it/iwt/Forum/CollaborativeSessionExportService/ReadCollaborativeSe" +
            "ssionData", ReplyAction="http://momanet.it/iwt/Forum/CollaborativeSessionExportService/ReadCollaborativeSe" +
            "ssionDataResponse")]
        Moma.IwtForumConverter.WsIwt.CollaborativeSession ReadCollaborativeSessionData(Moma.IwtForumConverter.WsIwt.CollaborativeSessionDescriptor cs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://momanet.it/iwt/Forum/CollaborativeSessionExportService/ReadUserAccounts", ReplyAction="http://momanet.it/iwt/Forum/CollaborativeSessionExportService/ReadUserAccountsRes" +
            "ponse")]
        System.Collections.Generic.List<Moma.IwtForumConverter.WsIwt.UserAccount> ReadUserAccounts(Moma.IwtForumConverter.WsIwt.CollaborativeSessionDescriptor cs);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://momanet.it/iwt/Forum/CollaborativeSessionExportService/ReadPosts", ReplyAction="http://momanet.it/iwt/Forum/CollaborativeSessionExportService/ReadPostsResponse")]
        System.Collections.Generic.List<Moma.IwtForumConverter.WsIwt.Message> ReadPosts(Moma.IwtForumConverter.WsIwt.CollaborativeSessionDescriptor cs);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CollaborativeSessionExportServiceChannel : Moma.IwtForumConverter.WsIwt.CollaborativeSessionExportService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CollaborativeSessionExportServiceClient : System.ServiceModel.ClientBase<Moma.IwtForumConverter.WsIwt.CollaborativeSessionExportService>, Moma.IwtForumConverter.WsIwt.CollaborativeSessionExportService {
        
        public CollaborativeSessionExportServiceClient() {
        }
        
        public CollaborativeSessionExportServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CollaborativeSessionExportServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CollaborativeSessionExportServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CollaborativeSessionExportServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<Moma.IwtForumConverter.WsIwt.CollaborativeSessionDescriptor> AvailableCollaborativeSessions() {
            return base.Channel.AvailableCollaborativeSessions();
        }
        
        public Moma.IwtForumConverter.WsIwt.CollaborativeSession ReadCollaborativeSessionData(Moma.IwtForumConverter.WsIwt.CollaborativeSessionDescriptor cs) {
            return base.Channel.ReadCollaborativeSessionData(cs);
        }
        
        public System.Collections.Generic.List<Moma.IwtForumConverter.WsIwt.UserAccount> ReadUserAccounts(Moma.IwtForumConverter.WsIwt.CollaborativeSessionDescriptor cs) {
            return base.Channel.ReadUserAccounts(cs);
        }
        
        public System.Collections.Generic.List<Moma.IwtForumConverter.WsIwt.Message> ReadPosts(Moma.IwtForumConverter.WsIwt.CollaborativeSessionDescriptor cs) {
            return base.Channel.ReadPosts(cs);
        }
    }
}
