//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 4.0.60310.0
// 
namespace VCS.SpeechService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SpeechService.ISpeechService")]
    public interface ISpeechService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ISpeechService/Speak", ReplyAction="http://tempuri.org/ISpeechService/SpeakResponse")]
        System.IAsyncResult BeginSpeak(string text, VCS.Gender gender, VCS.Age age, VCS.Language language, System.AsyncCallback callback, object asyncState);
        
        byte[] EndSpeak(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISpeechServiceChannel : VCS.SpeechService.ISpeechService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SpeakCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SpeakCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public byte[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SpeechServiceClient : System.ServiceModel.ClientBase<VCS.SpeechService.ISpeechService>, VCS.SpeechService.ISpeechService {
        
        private BeginOperationDelegate onBeginSpeakDelegate;
        
        private EndOperationDelegate onEndSpeakDelegate;
        
        private System.Threading.SendOrPostCallback onSpeakCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public SpeechServiceClient() {
        }
        
        public SpeechServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SpeechServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SpeechServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SpeechServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<SpeakCompletedEventArgs> SpeakCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult VCS.SpeechService.ISpeechService.BeginSpeak(string text, VCS.Gender gender, VCS.Age age, VCS.Language language, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSpeak(text, gender, age, language, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        byte[] VCS.SpeechService.ISpeechService.EndSpeak(System.IAsyncResult result) {
            return base.Channel.EndSpeak(result);
        }
        
        private System.IAsyncResult OnBeginSpeak(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string text = ((string)(inValues[0]));
            VCS.Gender gender = ((VCS.Gender)(inValues[1]));
            VCS.Age age = ((VCS.Age)(inValues[2]));
            VCS.Language language = ((VCS.Language)(inValues[3]));
            return ((VCS.SpeechService.ISpeechService)(this)).BeginSpeak(text, gender, age, language, callback, asyncState);
        }
        
        private object[] OnEndSpeak(System.IAsyncResult result) {
            byte[] retVal = ((VCS.SpeechService.ISpeechService)(this)).EndSpeak(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSpeakCompleted(object state) {
            if ((this.SpeakCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SpeakCompleted(this, new SpeakCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SpeakAsync(string text, VCS.Gender gender, VCS.Age age, VCS.Language language) {
            this.SpeakAsync(text, gender, age, language, null);
        }
        
        public void SpeakAsync(string text, VCS.Gender gender, VCS.Age age, VCS.Language language, object userState) {
            if ((this.onBeginSpeakDelegate == null)) {
                this.onBeginSpeakDelegate = new BeginOperationDelegate(this.OnBeginSpeak);
            }
            if ((this.onEndSpeakDelegate == null)) {
                this.onEndSpeakDelegate = new EndOperationDelegate(this.OnEndSpeak);
            }
            if ((this.onSpeakCompletedDelegate == null)) {
                this.onSpeakCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSpeakCompleted);
            }
            base.InvokeAsync(this.onBeginSpeakDelegate, new object[] {
                        text,
                        gender,
                        age,
                        language}, this.onEndSpeakDelegate, this.onSpeakCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override VCS.SpeechService.ISpeechService CreateChannel() {
            return new SpeechServiceClientChannel(this);
        }
        
        private class SpeechServiceClientChannel : ChannelBase<VCS.SpeechService.ISpeechService>, VCS.SpeechService.ISpeechService {
            
            public SpeechServiceClientChannel(System.ServiceModel.ClientBase<VCS.SpeechService.ISpeechService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginSpeak(string text, VCS.Gender gender, VCS.Age age, VCS.Language language, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[4];
                _args[0] = text;
                _args[1] = gender;
                _args[2] = age;
                _args[3] = language;
                System.IAsyncResult _result = base.BeginInvoke("Speak", _args, callback, asyncState);
                return _result;
            }
            
            public byte[] EndSpeak(System.IAsyncResult result) {
                object[] _args = new object[0];
                byte[] _result = ((byte[])(base.EndInvoke("Speak", _args, result)));
                return _result;
            }
        }
    }
}
