//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 4.0.60310.0
// 
namespace VCS.KeywordsRepositoryService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="KeywordsRepositoryService.IKeywordsRepositoryService")]
    public interface IKeywordsRepositoryService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/IKeywordsRepositoryService/GetAvailableKeywords", ReplyAction="http://tempuri.org/IKeywordsRepositoryService/GetAvailableKeywordsResponse")]
        System.IAsyncResult BeginGetAvailableKeywords(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<string> EndGetAvailableKeywords(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IKeywordsRepositoryServiceChannel : VCS.KeywordsRepositoryService.IKeywordsRepositoryService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAvailableKeywordsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAvailableKeywordsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<string> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<string>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KeywordsRepositoryServiceClient : System.ServiceModel.ClientBase<VCS.KeywordsRepositoryService.IKeywordsRepositoryService>, VCS.KeywordsRepositoryService.IKeywordsRepositoryService {
        
        private BeginOperationDelegate onBeginGetAvailableKeywordsDelegate;
        
        private EndOperationDelegate onEndGetAvailableKeywordsDelegate;
        
        private System.Threading.SendOrPostCallback onGetAvailableKeywordsCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public KeywordsRepositoryServiceClient() {
        }
        
        public KeywordsRepositoryServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KeywordsRepositoryServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KeywordsRepositoryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KeywordsRepositoryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetAvailableKeywordsCompletedEventArgs> GetAvailableKeywordsCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult VCS.KeywordsRepositoryService.IKeywordsRepositoryService.BeginGetAvailableKeywords(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAvailableKeywords(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<string> VCS.KeywordsRepositoryService.IKeywordsRepositoryService.EndGetAvailableKeywords(System.IAsyncResult result) {
            return base.Channel.EndGetAvailableKeywords(result);
        }
        
        private System.IAsyncResult OnBeginGetAvailableKeywords(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((VCS.KeywordsRepositoryService.IKeywordsRepositoryService)(this)).BeginGetAvailableKeywords(callback, asyncState);
        }
        
        private object[] OnEndGetAvailableKeywords(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<string> retVal = ((VCS.KeywordsRepositoryService.IKeywordsRepositoryService)(this)).EndGetAvailableKeywords(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAvailableKeywordsCompleted(object state) {
            if ((this.GetAvailableKeywordsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAvailableKeywordsCompleted(this, new GetAvailableKeywordsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAvailableKeywordsAsync() {
            this.GetAvailableKeywordsAsync(null);
        }
        
        public void GetAvailableKeywordsAsync(object userState) {
            if ((this.onBeginGetAvailableKeywordsDelegate == null)) {
                this.onBeginGetAvailableKeywordsDelegate = new BeginOperationDelegate(this.OnBeginGetAvailableKeywords);
            }
            if ((this.onEndGetAvailableKeywordsDelegate == null)) {
                this.onEndGetAvailableKeywordsDelegate = new EndOperationDelegate(this.OnEndGetAvailableKeywords);
            }
            if ((this.onGetAvailableKeywordsCompletedDelegate == null)) {
                this.onGetAvailableKeywordsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAvailableKeywordsCompleted);
            }
            base.InvokeAsync(this.onBeginGetAvailableKeywordsDelegate, null, this.onEndGetAvailableKeywordsDelegate, this.onGetAvailableKeywordsCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override VCS.KeywordsRepositoryService.IKeywordsRepositoryService CreateChannel() {
            return new KeywordsRepositoryServiceClientChannel(this);
        }
        
        private class KeywordsRepositoryServiceClientChannel : ChannelBase<VCS.KeywordsRepositoryService.IKeywordsRepositoryService>, VCS.KeywordsRepositoryService.IKeywordsRepositoryService {
            
            public KeywordsRepositoryServiceClientChannel(System.ServiceModel.ClientBase<VCS.KeywordsRepositoryService.IKeywordsRepositoryService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetAvailableKeywords(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetAvailableKeywords", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<string> EndGetAvailableKeywords(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<string> _result = ((System.Collections.ObjectModel.ObservableCollection<string>)(base.EndInvoke("GetAvailableKeywords", _args, result)));
                return _result;
            }
        }
    }
}
