//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 4.0.60310.0
// 
namespace VCS.AffectiveEmotiveServices {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EmotionalStateValue", Namespace="http://tempuri.org/")]
    public partial class EmotionalStateValue : object, System.ComponentModel.INotifyPropertyChanged {
        
        private double FidAnsField;
        
        private double IntDisField;
        
        private double EccIndField;
        
        private double AutFruField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double FidAns {
            get {
                return this.FidAnsField;
            }
            set {
                if ((this.FidAnsField.Equals(value) != true)) {
                    this.FidAnsField = value;
                    this.RaisePropertyChanged("FidAns");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double IntDis {
            get {
                return this.IntDisField;
            }
            set {
                if ((this.IntDisField.Equals(value) != true)) {
                    this.IntDisField = value;
                    this.RaisePropertyChanged("IntDis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public double EccInd {
            get {
                return this.EccIndField;
            }
            set {
                if ((this.EccIndField.Equals(value) != true)) {
                    this.EccIndField = value;
                    this.RaisePropertyChanged("EccInd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public double AutFru {
            get {
                return this.AutFruField;
            }
            set {
                if ((this.AutFruField.Equals(value) != true)) {
                    this.AutFruField = value;
                    this.RaisePropertyChanged("AutFru");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TESTTYPE", Namespace="http://tempuri.org/")]
    public enum TESTTYPE : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PREQUANTIFICATION = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        QUANTIFICATION = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AffectiveEmotiveServices.AffectiveEmotiveServicesSoap")]
    public interface AffectiveEmotiveServicesSoap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetLastUserEmotionalState", ReplyAction="*")]
        System.IAsyncResult BeginGetLastUserEmotionalState(VCS.AffectiveEmotiveServices.GetLastUserEmotionalStateRequest request, System.AsyncCallback callback, object asyncState);
        
        VCS.AffectiveEmotiveServices.GetLastUserEmotionalStateResponse EndGetLastUserEmotionalState(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetLastUserEmotionalStateWithoutIdCourse", ReplyAction="*")]
        System.IAsyncResult BeginGetLastUserEmotionalState1(VCS.AffectiveEmotiveServices.GetLastUserEmotionalStateWithoutIdCourse request, System.AsyncCallback callback, object asyncState);
        
        VCS.AffectiveEmotiveServices.GetLastUserEmotionalStateWithoutIdCourse1 EndGetLastUserEmotionalState1(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/SetUserEmotionalState", ReplyAction="*")]
        System.IAsyncResult BeginSetUserEmotionalState(VCS.AffectiveEmotiveServices.SetUserEmotionalStateRequest request, System.AsyncCallback callback, object asyncState);
        
        VCS.AffectiveEmotiveServices.SetUserEmotionalStateResponse EndSetUserEmotionalState(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/SetUserEmotionalStateWithTestType", ReplyAction="*")]
        System.IAsyncResult BeginSetUserEmotionalState1(VCS.AffectiveEmotiveServices.SetUserEmotionalStateWithTestType request, System.AsyncCallback callback, object asyncState);
        
        VCS.AffectiveEmotiveServices.SetUserEmotionalStateWithTestType1 EndSetUserEmotionalState1(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLastUserEmotionalStateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLastUserEmotionalState", Namespace="http://tempuri.org/", Order=0)]
        public VCS.AffectiveEmotiveServices.GetLastUserEmotionalStateRequestBody Body;
        
        public GetLastUserEmotionalStateRequest() {
        }
        
        public GetLastUserEmotionalStateRequest(VCS.AffectiveEmotiveServices.GetLastUserEmotionalStateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetLastUserEmotionalStateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idUser;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int idCourse;
        
        public GetLastUserEmotionalStateRequestBody() {
        }
        
        public GetLastUserEmotionalStateRequestBody(int idUser, int idCourse) {
            this.idUser = idUser;
            this.idCourse = idCourse;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLastUserEmotionalStateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLastUserEmotionalStateResponse", Namespace="http://tempuri.org/", Order=0)]
        public VCS.AffectiveEmotiveServices.GetLastUserEmotionalStateResponseBody Body;
        
        public GetLastUserEmotionalStateResponse() {
        }
        
        public GetLastUserEmotionalStateResponse(VCS.AffectiveEmotiveServices.GetLastUserEmotionalStateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetLastUserEmotionalStateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public VCS.AffectiveEmotiveServices.EmotionalStateValue GetLastUserEmotionalStateResult;
        
        public GetLastUserEmotionalStateResponseBody() {
        }
        
        public GetLastUserEmotionalStateResponseBody(VCS.AffectiveEmotiveServices.EmotionalStateValue GetLastUserEmotionalStateResult) {
            this.GetLastUserEmotionalStateResult = GetLastUserEmotionalStateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetLastUserEmotionalStateWithoutIdCourse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetLastUserEmotionalStateWithoutIdCourse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int idUser;
        
        public GetLastUserEmotionalStateWithoutIdCourse() {
        }
        
        public GetLastUserEmotionalStateWithoutIdCourse(int idUser) {
            this.idUser = idUser;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetLastUserEmotionalStateWithoutIdCourseResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetLastUserEmotionalStateWithoutIdCourse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetLastUserEmotionalStateWithoutIdCourseResult;
        
        public GetLastUserEmotionalStateWithoutIdCourse1() {
        }
        
        public GetLastUserEmotionalStateWithoutIdCourse1(string GetLastUserEmotionalStateWithoutIdCourseResult) {
            this.GetLastUserEmotionalStateWithoutIdCourseResult = GetLastUserEmotionalStateWithoutIdCourseResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetUserEmotionalStateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetUserEmotionalState", Namespace="http://tempuri.org/", Order=0)]
        public VCS.AffectiveEmotiveServices.SetUserEmotionalStateRequestBody Body;
        
        public SetUserEmotionalStateRequest() {
        }
        
        public SetUserEmotionalStateRequest(VCS.AffectiveEmotiveServices.SetUserEmotionalStateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetUserEmotionalStateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idUser;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int idCourse;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public VCS.AffectiveEmotiveServices.EmotionalStateValue value;
        
        public SetUserEmotionalStateRequestBody() {
        }
        
        public SetUserEmotionalStateRequestBody(int idUser, int idCourse, VCS.AffectiveEmotiveServices.EmotionalStateValue value) {
            this.idUser = idUser;
            this.idCourse = idCourse;
            this.value = value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetUserEmotionalStateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetUserEmotionalStateResponse", Namespace="http://tempuri.org/", Order=0)]
        public VCS.AffectiveEmotiveServices.SetUserEmotionalStateResponseBody Body;
        
        public SetUserEmotionalStateResponse() {
        }
        
        public SetUserEmotionalStateResponse(VCS.AffectiveEmotiveServices.SetUserEmotionalStateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SetUserEmotionalStateResponseBody {
        
        public SetUserEmotionalStateResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetUserEmotionalStateWithTestType", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SetUserEmotionalStateWithTestType {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int idUser;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int idCourse;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public VCS.AffectiveEmotiveServices.EmotionalStateValue value;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public VCS.AffectiveEmotiveServices.TESTTYPE testType;
        
        public SetUserEmotionalStateWithTestType() {
        }
        
        public SetUserEmotionalStateWithTestType(int idUser, int idCourse, VCS.AffectiveEmotiveServices.EmotionalStateValue value, VCS.AffectiveEmotiveServices.TESTTYPE testType) {
            this.idUser = idUser;
            this.idCourse = idCourse;
            this.value = value;
            this.testType = testType;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetUserEmotionalStateWithTestTypeResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SetUserEmotionalStateWithTestType1 {
        
        public SetUserEmotionalStateWithTestType1() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AffectiveEmotiveServicesSoapChannel : VCS.AffectiveEmotiveServices.AffectiveEmotiveServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetLastUserEmotionalStateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetLastUserEmotionalStateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public VCS.AffectiveEmotiveServices.EmotionalStateValue Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((VCS.AffectiveEmotiveServices.EmotionalStateValue)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetLastUserEmotionalState1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetLastUserEmotionalState1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AffectiveEmotiveServicesSoapClient : System.ServiceModel.ClientBase<VCS.AffectiveEmotiveServices.AffectiveEmotiveServicesSoap>, VCS.AffectiveEmotiveServices.AffectiveEmotiveServicesSoap {
        
        private BeginOperationDelegate onBeginGetLastUserEmotionalStateDelegate;
        
        private EndOperationDelegate onEndGetLastUserEmotionalStateDelegate;
        
        private System.Threading.SendOrPostCallback onGetLastUserEmotionalStateCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetLastUserEmotionalState1Delegate;
        
        private EndOperationDelegate onEndGetLastUserEmotionalState1Delegate;
        
        private System.Threading.SendOrPostCallback onGetLastUserEmotionalState1CompletedDelegate;
        
        private BeginOperationDelegate onBeginSetUserEmotionalStateDelegate;
        
        private EndOperationDelegate onEndSetUserEmotionalStateDelegate;
        
        private System.Threading.SendOrPostCallback onSetUserEmotionalStateCompletedDelegate;
        
        private BeginOperationDelegate onBeginSetUserEmotionalState1Delegate;
        
        private EndOperationDelegate onEndSetUserEmotionalState1Delegate;
        
        private System.Threading.SendOrPostCallback onSetUserEmotionalState1CompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public AffectiveEmotiveServicesSoapClient() {
        }
        
        public AffectiveEmotiveServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AffectiveEmotiveServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AffectiveEmotiveServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AffectiveEmotiveServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetLastUserEmotionalStateCompletedEventArgs> GetLastUserEmotionalStateCompleted;
        
        public event System.EventHandler<GetLastUserEmotionalState1CompletedEventArgs> GetLastUserEmotionalState1Completed;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> SetUserEmotionalStateCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> SetUserEmotionalState1Completed;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult VCS.AffectiveEmotiveServices.AffectiveEmotiveServicesSoap.BeginGetLastUserEmotionalState(VCS.AffectiveEmotiveServices.GetLastUserEmotionalStateRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetLastUserEmotionalState(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetLastUserEmotionalState(int idUser, int idCourse, System.AsyncCallback callback, object asyncState) {
            VCS.AffectiveEmotiveServices.GetLastUserEmotionalStateRequest inValue = new VCS.AffectiveEmotiveServices.GetLastUserEmotionalStateRequest();
            inValue.Body = new VCS.AffectiveEmotiveServices.GetLastUserEmotionalStateRequestBody();
            inValue.Body.idUser = idUser;
            inValue.Body.idCourse = idCourse;
            return ((VCS.AffectiveEmotiveServices.AffectiveEmotiveServicesSoap)(this)).BeginGetLastUserEmotionalState(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VCS.AffectiveEmotiveServices.GetLastUserEmotionalStateResponse VCS.AffectiveEmotiveServices.AffectiveEmotiveServicesSoap.EndGetLastUserEmotionalState(System.IAsyncResult result) {
            return base.Channel.EndGetLastUserEmotionalState(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private VCS.AffectiveEmotiveServices.EmotionalStateValue EndGetLastUserEmotionalState(System.IAsyncResult result) {
            VCS.AffectiveEmotiveServices.GetLastUserEmotionalStateResponse retVal = ((VCS.AffectiveEmotiveServices.AffectiveEmotiveServicesSoap)(this)).EndGetLastUserEmotionalState(result);
            return retVal.Body.GetLastUserEmotionalStateResult;
        }
        
        private System.IAsyncResult OnBeginGetLastUserEmotionalState(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int idUser = ((int)(inValues[0]));
            int idCourse = ((int)(inValues[1]));
            return this.BeginGetLastUserEmotionalState(idUser, idCourse, callback, asyncState);
        }
        
        private object[] OnEndGetLastUserEmotionalState(System.IAsyncResult result) {
            VCS.AffectiveEmotiveServices.EmotionalStateValue retVal = this.EndGetLastUserEmotionalState(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetLastUserEmotionalStateCompleted(object state) {
            if ((this.GetLastUserEmotionalStateCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetLastUserEmotionalStateCompleted(this, new GetLastUserEmotionalStateCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetLastUserEmotionalStateAsync(int idUser, int idCourse) {
            this.GetLastUserEmotionalStateAsync(idUser, idCourse, null);
        }
        
        public void GetLastUserEmotionalStateAsync(int idUser, int idCourse, object userState) {
            if ((this.onBeginGetLastUserEmotionalStateDelegate == null)) {
                this.onBeginGetLastUserEmotionalStateDelegate = new BeginOperationDelegate(this.OnBeginGetLastUserEmotionalState);
            }
            if ((this.onEndGetLastUserEmotionalStateDelegate == null)) {
                this.onEndGetLastUserEmotionalStateDelegate = new EndOperationDelegate(this.OnEndGetLastUserEmotionalState);
            }
            if ((this.onGetLastUserEmotionalStateCompletedDelegate == null)) {
                this.onGetLastUserEmotionalStateCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetLastUserEmotionalStateCompleted);
            }
            base.InvokeAsync(this.onBeginGetLastUserEmotionalStateDelegate, new object[] {
                        idUser,
                        idCourse}, this.onEndGetLastUserEmotionalStateDelegate, this.onGetLastUserEmotionalStateCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult VCS.AffectiveEmotiveServices.AffectiveEmotiveServicesSoap.BeginGetLastUserEmotionalState1(VCS.AffectiveEmotiveServices.GetLastUserEmotionalStateWithoutIdCourse request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetLastUserEmotionalState1(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetLastUserEmotionalState1(int idUser, System.AsyncCallback callback, object asyncState) {
            VCS.AffectiveEmotiveServices.GetLastUserEmotionalStateWithoutIdCourse inValue = new VCS.AffectiveEmotiveServices.GetLastUserEmotionalStateWithoutIdCourse();
            inValue.idUser = idUser;
            return ((VCS.AffectiveEmotiveServices.AffectiveEmotiveServicesSoap)(this)).BeginGetLastUserEmotionalState1(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VCS.AffectiveEmotiveServices.GetLastUserEmotionalStateWithoutIdCourse1 VCS.AffectiveEmotiveServices.AffectiveEmotiveServicesSoap.EndGetLastUserEmotionalState1(System.IAsyncResult result) {
            return base.Channel.EndGetLastUserEmotionalState1(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndGetLastUserEmotionalState1(System.IAsyncResult result) {
            VCS.AffectiveEmotiveServices.GetLastUserEmotionalStateWithoutIdCourse1 retVal = ((VCS.AffectiveEmotiveServices.AffectiveEmotiveServicesSoap)(this)).EndGetLastUserEmotionalState1(result);
            return retVal.GetLastUserEmotionalStateWithoutIdCourseResult;
        }
        
        private System.IAsyncResult OnBeginGetLastUserEmotionalState1(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int idUser = ((int)(inValues[0]));
            return this.BeginGetLastUserEmotionalState1(idUser, callback, asyncState);
        }
        
        private object[] OnEndGetLastUserEmotionalState1(System.IAsyncResult result) {
            string retVal = this.EndGetLastUserEmotionalState1(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetLastUserEmotionalState1Completed(object state) {
            if ((this.GetLastUserEmotionalState1Completed != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetLastUserEmotionalState1Completed(this, new GetLastUserEmotionalState1CompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetLastUserEmotionalState1Async(int idUser) {
            this.GetLastUserEmotionalState1Async(idUser, null);
        }
        
        public void GetLastUserEmotionalState1Async(int idUser, object userState) {
            if ((this.onBeginGetLastUserEmotionalState1Delegate == null)) {
                this.onBeginGetLastUserEmotionalState1Delegate = new BeginOperationDelegate(this.OnBeginGetLastUserEmotionalState1);
            }
            if ((this.onEndGetLastUserEmotionalState1Delegate == null)) {
                this.onEndGetLastUserEmotionalState1Delegate = new EndOperationDelegate(this.OnEndGetLastUserEmotionalState1);
            }
            if ((this.onGetLastUserEmotionalState1CompletedDelegate == null)) {
                this.onGetLastUserEmotionalState1CompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetLastUserEmotionalState1Completed);
            }
            base.InvokeAsync(this.onBeginGetLastUserEmotionalState1Delegate, new object[] {
                        idUser}, this.onEndGetLastUserEmotionalState1Delegate, this.onGetLastUserEmotionalState1CompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult VCS.AffectiveEmotiveServices.AffectiveEmotiveServicesSoap.BeginSetUserEmotionalState(VCS.AffectiveEmotiveServices.SetUserEmotionalStateRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSetUserEmotionalState(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginSetUserEmotionalState(int idUser, int idCourse, VCS.AffectiveEmotiveServices.EmotionalStateValue value, System.AsyncCallback callback, object asyncState) {
            VCS.AffectiveEmotiveServices.SetUserEmotionalStateRequest inValue = new VCS.AffectiveEmotiveServices.SetUserEmotionalStateRequest();
            inValue.Body = new VCS.AffectiveEmotiveServices.SetUserEmotionalStateRequestBody();
            inValue.Body.idUser = idUser;
            inValue.Body.idCourse = idCourse;
            inValue.Body.value = value;
            return ((VCS.AffectiveEmotiveServices.AffectiveEmotiveServicesSoap)(this)).BeginSetUserEmotionalState(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VCS.AffectiveEmotiveServices.SetUserEmotionalStateResponse VCS.AffectiveEmotiveServices.AffectiveEmotiveServicesSoap.EndSetUserEmotionalState(System.IAsyncResult result) {
            return base.Channel.EndSetUserEmotionalState(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private void EndSetUserEmotionalState(System.IAsyncResult result) {
            VCS.AffectiveEmotiveServices.SetUserEmotionalStateResponse retVal = ((VCS.AffectiveEmotiveServices.AffectiveEmotiveServicesSoap)(this)).EndSetUserEmotionalState(result);
        }
        
        private System.IAsyncResult OnBeginSetUserEmotionalState(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int idUser = ((int)(inValues[0]));
            int idCourse = ((int)(inValues[1]));
            VCS.AffectiveEmotiveServices.EmotionalStateValue value = ((VCS.AffectiveEmotiveServices.EmotionalStateValue)(inValues[2]));
            return this.BeginSetUserEmotionalState(idUser, idCourse, value, callback, asyncState);
        }
        
        private object[] OnEndSetUserEmotionalState(System.IAsyncResult result) {
            this.EndSetUserEmotionalState(result);
            return null;
        }
        
        private void OnSetUserEmotionalStateCompleted(object state) {
            if ((this.SetUserEmotionalStateCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SetUserEmotionalStateCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SetUserEmotionalStateAsync(int idUser, int idCourse, VCS.AffectiveEmotiveServices.EmotionalStateValue value) {
            this.SetUserEmotionalStateAsync(idUser, idCourse, value, null);
        }
        
        public void SetUserEmotionalStateAsync(int idUser, int idCourse, VCS.AffectiveEmotiveServices.EmotionalStateValue value, object userState) {
            if ((this.onBeginSetUserEmotionalStateDelegate == null)) {
                this.onBeginSetUserEmotionalStateDelegate = new BeginOperationDelegate(this.OnBeginSetUserEmotionalState);
            }
            if ((this.onEndSetUserEmotionalStateDelegate == null)) {
                this.onEndSetUserEmotionalStateDelegate = new EndOperationDelegate(this.OnEndSetUserEmotionalState);
            }
            if ((this.onSetUserEmotionalStateCompletedDelegate == null)) {
                this.onSetUserEmotionalStateCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSetUserEmotionalStateCompleted);
            }
            base.InvokeAsync(this.onBeginSetUserEmotionalStateDelegate, new object[] {
                        idUser,
                        idCourse,
                        value}, this.onEndSetUserEmotionalStateDelegate, this.onSetUserEmotionalStateCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult VCS.AffectiveEmotiveServices.AffectiveEmotiveServicesSoap.BeginSetUserEmotionalState1(VCS.AffectiveEmotiveServices.SetUserEmotionalStateWithTestType request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSetUserEmotionalState1(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginSetUserEmotionalState1(int idUser, int idCourse, VCS.AffectiveEmotiveServices.EmotionalStateValue value, VCS.AffectiveEmotiveServices.TESTTYPE testType, System.AsyncCallback callback, object asyncState) {
            VCS.AffectiveEmotiveServices.SetUserEmotionalStateWithTestType inValue = new VCS.AffectiveEmotiveServices.SetUserEmotionalStateWithTestType();
            inValue.idUser = idUser;
            inValue.idCourse = idCourse;
            inValue.value = value;
            inValue.testType = testType;
            return ((VCS.AffectiveEmotiveServices.AffectiveEmotiveServicesSoap)(this)).BeginSetUserEmotionalState1(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VCS.AffectiveEmotiveServices.SetUserEmotionalStateWithTestType1 VCS.AffectiveEmotiveServices.AffectiveEmotiveServicesSoap.EndSetUserEmotionalState1(System.IAsyncResult result) {
            return base.Channel.EndSetUserEmotionalState1(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private void EndSetUserEmotionalState1(System.IAsyncResult result) {
            VCS.AffectiveEmotiveServices.SetUserEmotionalStateWithTestType1 retVal = ((VCS.AffectiveEmotiveServices.AffectiveEmotiveServicesSoap)(this)).EndSetUserEmotionalState1(result);
        }
        
        private System.IAsyncResult OnBeginSetUserEmotionalState1(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int idUser = ((int)(inValues[0]));
            int idCourse = ((int)(inValues[1]));
            VCS.AffectiveEmotiveServices.EmotionalStateValue value = ((VCS.AffectiveEmotiveServices.EmotionalStateValue)(inValues[2]));
            VCS.AffectiveEmotiveServices.TESTTYPE testType = ((VCS.AffectiveEmotiveServices.TESTTYPE)(inValues[3]));
            return this.BeginSetUserEmotionalState1(idUser, idCourse, value, testType, callback, asyncState);
        }
        
        private object[] OnEndSetUserEmotionalState1(System.IAsyncResult result) {
            this.EndSetUserEmotionalState1(result);
            return null;
        }
        
        private void OnSetUserEmotionalState1Completed(object state) {
            if ((this.SetUserEmotionalState1Completed != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SetUserEmotionalState1Completed(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SetUserEmotionalState1Async(int idUser, int idCourse, VCS.AffectiveEmotiveServices.EmotionalStateValue value, VCS.AffectiveEmotiveServices.TESTTYPE testType) {
            this.SetUserEmotionalState1Async(idUser, idCourse, value, testType, null);
        }
        
        public void SetUserEmotionalState1Async(int idUser, int idCourse, VCS.AffectiveEmotiveServices.EmotionalStateValue value, VCS.AffectiveEmotiveServices.TESTTYPE testType, object userState) {
            if ((this.onBeginSetUserEmotionalState1Delegate == null)) {
                this.onBeginSetUserEmotionalState1Delegate = new BeginOperationDelegate(this.OnBeginSetUserEmotionalState1);
            }
            if ((this.onEndSetUserEmotionalState1Delegate == null)) {
                this.onEndSetUserEmotionalState1Delegate = new EndOperationDelegate(this.OnEndSetUserEmotionalState1);
            }
            if ((this.onSetUserEmotionalState1CompletedDelegate == null)) {
                this.onSetUserEmotionalState1CompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSetUserEmotionalState1Completed);
            }
            base.InvokeAsync(this.onBeginSetUserEmotionalState1Delegate, new object[] {
                        idUser,
                        idCourse,
                        value,
                        testType}, this.onEndSetUserEmotionalState1Delegate, this.onSetUserEmotionalState1CompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override VCS.AffectiveEmotiveServices.AffectiveEmotiveServicesSoap CreateChannel() {
            return new AffectiveEmotiveServicesSoapClientChannel(this);
        }
        
        private class AffectiveEmotiveServicesSoapClientChannel : ChannelBase<VCS.AffectiveEmotiveServices.AffectiveEmotiveServicesSoap>, VCS.AffectiveEmotiveServices.AffectiveEmotiveServicesSoap {
            
            public AffectiveEmotiveServicesSoapClientChannel(System.ServiceModel.ClientBase<VCS.AffectiveEmotiveServices.AffectiveEmotiveServicesSoap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetLastUserEmotionalState(VCS.AffectiveEmotiveServices.GetLastUserEmotionalStateRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetLastUserEmotionalState", _args, callback, asyncState);
                return _result;
            }
            
            public VCS.AffectiveEmotiveServices.GetLastUserEmotionalStateResponse EndGetLastUserEmotionalState(System.IAsyncResult result) {
                object[] _args = new object[0];
                VCS.AffectiveEmotiveServices.GetLastUserEmotionalStateResponse _result = ((VCS.AffectiveEmotiveServices.GetLastUserEmotionalStateResponse)(base.EndInvoke("GetLastUserEmotionalState", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetLastUserEmotionalState1(VCS.AffectiveEmotiveServices.GetLastUserEmotionalStateWithoutIdCourse request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetLastUserEmotionalState1", _args, callback, asyncState);
                return _result;
            }
            
            public VCS.AffectiveEmotiveServices.GetLastUserEmotionalStateWithoutIdCourse1 EndGetLastUserEmotionalState1(System.IAsyncResult result) {
                object[] _args = new object[0];
                VCS.AffectiveEmotiveServices.GetLastUserEmotionalStateWithoutIdCourse1 _result = ((VCS.AffectiveEmotiveServices.GetLastUserEmotionalStateWithoutIdCourse1)(base.EndInvoke("GetLastUserEmotionalState1", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginSetUserEmotionalState(VCS.AffectiveEmotiveServices.SetUserEmotionalStateRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("SetUserEmotionalState", _args, callback, asyncState);
                return _result;
            }
            
            public VCS.AffectiveEmotiveServices.SetUserEmotionalStateResponse EndSetUserEmotionalState(System.IAsyncResult result) {
                object[] _args = new object[0];
                VCS.AffectiveEmotiveServices.SetUserEmotionalStateResponse _result = ((VCS.AffectiveEmotiveServices.SetUserEmotionalStateResponse)(base.EndInvoke("SetUserEmotionalState", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginSetUserEmotionalState1(VCS.AffectiveEmotiveServices.SetUserEmotionalStateWithTestType request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("SetUserEmotionalState1", _args, callback, asyncState);
                return _result;
            }
            
            public VCS.AffectiveEmotiveServices.SetUserEmotionalStateWithTestType1 EndSetUserEmotionalState1(System.IAsyncResult result) {
                object[] _args = new object[0];
                VCS.AffectiveEmotiveServices.SetUserEmotionalStateWithTestType1 _result = ((VCS.AffectiveEmotiveServices.SetUserEmotionalStateWithTestType1)(base.EndInvoke("SetUserEmotionalState1", _args, result)));
                return _result;
            }
        }
    }
}
